name: Trigger Mark6 Check

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_mark6] 

jobs:
  call-google-script:
    runs-on: ubuntu-latest
    steps:
      - name: Call Google Apps Script WebApp
        run: |
          curl -L -s "${{ secrets.MARK6_URL }}"
